server:
  port: 9000
spring:
  application:
    name: manager-application
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
    instance:
      prefer-ip-address: true
zuul:
  routes:
    soft-application: #软件
      path: /soft/** #配置请求URL的请求规则
      serviceId: soft-application #指定Eureka注册中心中的服务id
    classify-application: #类别
      path: /classify/** #配置请求URL的请求规则
      serviceId: classify-application #指定Eureka注册中心中的服务id
    comment-application: #评论
      path: /comment/** #配置请求URL的请求规则
      serviceId: comment-application #指定Eureka注册中心中的服务id
    tutorial-application: #教程
      path: /tutorial/** #配置请求URL的请求规则
      serviceId: tutorial-application #指定Eureka注册中心中的服务id
    user-application: #用户
      path: /user/** #配置请求URL的请求规则
      serviceId: user-application #指定Eureka注册中心中的服务id
    admin-application: #管理员
      path: /admin/** #配置请求URL的请求规则
      serviceId: admin-application #指定Eureka注册中心中的服务id
    carousel-application: #轮播图
      path: /carousel/**
      serviceId: carousel-application
    college-application: #学院
      path: /college/**
      serviceId: college-application
    statistics-application: #统计
      path: /statistics/**
      serviceId: statistics-application
ribbon:
  ReadTimeout: 600000
  ConnectTimeout: 600000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1



