server:
  port: 9006
spring:
  application:
    name: admin-application
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Huangtong1998...
    url: jdbc:mysql://47.102.120.6:3306/software?characterEncoding=utf-8
jwt:
  config:
    key: huangtong  #秘钥
    ttl: 360000 #一个小时