server:
  port: 9001
spring:
  application:
    name: soft-application
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/software?characterEncoding=utf-8

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true

jwt:
  config:
    key: huangtong  #秘钥
    ttl: 3600000 #一个小时60 60 3600000 60*60*1000
fastdf:
  ip: http://192.168.98.132/
