server:
  port: 9007
spring:
  application:
    name: carousel-application
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Huangtong1998...
    url: jdbc:mysql://47.102.120.6:3306/software?characterEncoding=utf-8

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true

jwt:
  config:
    key: huangtong  #秘钥
    ttl: 3600000 #一个小时60 60 3600000
fastdf:
  ip: http://192.168.98.132/
