server:
  port: 9001
spring:
  application:
    name: soft-application
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Huangtong1998...
    url: jdbc:mysql://47.102.120.6:3306/software?characterEncoding=utf-8
jwt:
  config:
    key: huangtong  #秘钥
    ttl: 3600000 #一个小时60 60 3600000
fastdf:
  ip: http://192.168.98.132/