server:
  port: 9003
spring:
  application:
    name: comment-application
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Huangtong1998...
    url: jdbc:mysql://47.102.120.6:3306/software?characterEncoding=utf-8